# ESLint check
name: ESLint check
on: [push]
# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint