# ESLint check
name: ESLint check and codacy check
on: [push]
# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]
jobs:
# job 1
  ESLint-check:
    name: ESLint-check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: setup node js
      uses: actions/setup-node@v2
      with:
        node-version: "16"
    - name: install all dependencies
      run: npm install
    - name: run ESlint checking
      run: npm run lint

# job 2
  codacy-check:
      name: codacy-check
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master